### ISSUE TITLE
[Bug]: AC60P not work

### ISSUE THREAD

**Issue by vpk911** [Patrick762/hassio-bluetti-bt#121]
### What happened?

object is not subscriptable

### What version of our software are you running?

0.1.2

### What device are you seeing the problem on?

Error setting up entry AC60P************************* for bluetti_bt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/__init__.py", line 59, in async_setup_entry
    coordinator = PollingCoordinator(hass, address, device_name, polling_interval, persistent_conn, polling_timeout, max_retries)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 54, in __init__
    bluetti_device = build_device(address, device_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/bluetti_bt_lib/utils/device_builder.py", line 28, in build_device
    if match[1] == "AC60":
       ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

### What bluetooth connection are you using?

Internal bluetooth adapter

### Have you changed the integration settings?

Yes (Please write down the changed settings in the next step)

### Integration settings (if you changed them)

```text
Persistent connection (restart required) on/off
```


### Relevant log output

_No response_

**Comment by tnufire** [comment]
Hello,

I was able to get my AC60P working with HA by adding "P?" to the regex in the following from device_builder.py:

> DEVICE_NAME_RE = re.compile(
>     r"^(AC60|AC70|AC70P|AC180|AC180P|AC200L|AC200M|AC300|AC500|EB3A|EP500|EP500P|EP600|EP760|EP800)**P?**(\d+)$"
> )

This updated regex treats my AC60P (and any other model with a P suffix on the model name) just like the base model. This is correct for the AC60P since, to the best of my knowledge, the "P“ just means it has a slightly larger battery (504 vs 403 Wh) along with orange accents and IP65 badging. The AC60 and AC60P both have the same dustproof & water-resistant certification so the new IP65 badging is cosmetic, not a change to the design.

My AC60P now exposes HA sensors for "Total Battery Percent" and "Total Power Generation." From the code related to the AC60, this appears to be the expected behavior. It would, of course, be great to get additional sensors like AC/DC on/off, power in/out, etc., which are exposed via Bluetti's iOS app.

My change may also add support for the AC200P and EB200P variants, which the updated regex will treat like their base models. I think the “P” suffix in Bluetti’s model names denotes their Premium Series, which may include improvements in battery capacity, design, or other features over the standard models. That said, I'm not sure if this will actually work since I only have an AC60P to test. 

Also, since the original regex has EP500P explicitly listed, I don't think my edit changes the behavior for that model (regex should be greedy and match the longest string possible in the 1st clause), but that should, of course, be tested as well.

Hope this helps,

Cheers,
Tim

**Comment by noobshoes** [comment]
This worked perfectly to get my AC60P up and running too. But only with the two options you had too. I have now installed this fork which provides control for almost anything:

 https://github.com/mzpwr/hassio-bluetti-bt?tab=readme-ov-file 

The HACS button in the fork installs the standard version from Patrick so you need to manually add the github to HACS and download that way.
