### ISSUE TITLE
Please, add AC2A support. Thanks in advance

### ISSUE THREAD

**Issue by pavlyuchenko-ua** [Patrick762/hassio-bluetti-bt#131]
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 7:19:02 PM (1 occurrences)
Last logged: 7:19:02 PM

Error setting up entry AC2A2347006029813 for bluetti_bt
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/__init__.py", line 59, in async_setup_entry
    coordinator = PollingCoordinator(hass, address, device_name, polling_interval, persistent_conn, polling_timeout, max_retries)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 54, in __init__
    bluetti_device = build_device(address, device_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/bluetti_bt_lib/utils/device_builder.py", line 28, in build_device
    if match[1] == "AC60":
       ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by PaulLacatus** [comment]
I am also interested , can be done ?

**Comment by mikwhe** [comment]
I've been working on backward engineering AC2A device for months and can now confirm this can work.
I'm unsure how to contribute to project however below is a summary of the important steps which hopefully author can apply sometime:
1) I needed to create ac2a.py file in devices folder and add to list of compatible devices
2) I then discovered and mapped the device registers as below:
        self.struct.add_uint_field('total_battery_percent', 102)
        self.struct.add_swap_string_field('device_type', 110, 6)
        self.struct.add_sn_field('serial_number', 116)
        self.struct.add_decimal_field('power_generation', 154, 1)  # Total power generated since last reset (kwh)

        self.struct.add_uint_field('dc_output_power', 140)
        self.struct.add_uint_field('ac_output_power', 142)
        self.struct.add_uint_field('dc_input_power', 144)
        self.struct.add_uint_field('ac_input_power', 146)
        self.struct.add_bool_field('ac_output_on', 1509)
        self.struct.add_bool_field('dc_output_on', 2012)
        self.struct.add_bool_field('power_lifting_on', 2021)
 
 Hopefully this helps make an already excellent tool a bit better

**Comment by PetePeter** [comment]
oh man. i got my ac2a and then discovered this doesnt work yet :(
ohwell, one day maybe.

**Comment by LUNCHBOX115** [comment]
trying to customise this for AC2A. How long?

**Comment by tux43** [comment]
> I've been working on backward engineering AC2A device for months and can now confirm this can work. I'm unsure how to contribute to project however below is a summary of the important steps which hopefully author can apply sometime:
> 
> 1. I needed to create ac2a.py file in devices folder and add to list of compatible devices
> 2. I then discovered and mapped the device registers as below:
>    self.struct.add_uint_field('total_battery_percent', 102)
>    self.struct.add_swap_string_field('device_type', 110, 6)
>    self.struct.add_sn_field('serial_number', 116)
>    self.struct.add_decimal_field('power_generation', 154, 1)  # Total power generated since last reset (kwh)
>    ```
>     self.struct.add_uint_field('dc_output_power', 140)
>     self.struct.add_uint_field('ac_output_power', 142)
>     self.struct.add_uint_field('dc_input_power', 144)
>     self.struct.add_uint_field('ac_input_power', 146)
>     self.struct.add_bool_field('ac_output_on', 1509)
>     self.struct.add_bool_field('dc_output_on', 2012)
>     self.struct.add_bool_field('power_lifting_on', 2021)
>    ```
> 
> Hopefully this helps make an already excellent tool a bit better

I've followed these steps, including https://github.com/Patrick762/hassio-bluetti-bt/pull/179 however this isn't working. Can anybody confirm success?
