### ISSUE TITLE
[Bug]: EP500pro connection trouble, but device works so far

### ISSUE THREAD

**Issue by TobiGitHubi** [Patrick762/hassio-bluetti-bt#149]
### What happened?

Various error messages in the CORE-Log

### What version of our software are you running?

HA 2024.12.5 all systems with the last software/firmware

System is working perfect until the december updates of HA (2024.12.x)

### What device are you seeing the problem on?

EP 500pro, connected with BT to a RasPi5 HomeAssistant device nearby. (1m range)

### What bluetooth connection are you using?

Internal bluetooth adapter

### Have you changed the integration settings?

Yes (Please write down the changed settings in the next step)

### Integration settings (if you changed them)

```text
changed mode from mqtt to discovery, but didn´t help, so switched back to mqtt

the integration works with standard settings, nothing else was changed
```

### Relevant log output

```shell
Error1:
Logger: custom_components.bluetti_bt.coordinator
Quelle: helpers/update_coordinator.py:379
Integration: Bluetti BT (Dokumentation, Probleme)
Erstmals aufgetreten: 28. Dezember 2024 um 14:36:13 (14 Vorkommnisse)
Zuletzt protokolliert: 03:27:19
Unexpected error fetching Bluetti polling coordinator data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 78, in _async_update_data
    return await self.reader.read_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py", line 155, in read_data
    await self.client.disconnect()
  File "/usr/local/lib/python3.13/site-packages/habluetooth/wrappers.py", line 404, in disconnect
    return await self._backend.disconnect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 409, in disconnect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/dbus_fast/aio/message_bus.py", line 385, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 19, in dbus_fast.aio.message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 775, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 636, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 374, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 317, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
EOFError

Error2:
Logger: custom_components.bluetti_bt.coordinator
Quelle: custom_components/bluetti_bt/coordinator.py:74
Integration: Bluetti BT (Dokumentation, Probleme)
Erstmals aufgetreten: 00:57:21 (7 Vorkommnisse)
Zuletzt protokolliert: 00:59:21
Device not connected

Error3:
Logger: custom_components.bluetti_bt.bluetti_bt_lib.bluetooth.device_reader
Quelle: custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py:143
Integration: Bluetti BT (Dokumentation, Probleme)
Erstmals aufgetreten: 00:57:01 (1 Vorkommnisse)
Zuletzt protokolliert: 00:57:01
Bleak error: No backend with an available connection slot that can reach address 94:E6:86:07:A6:66 was found

Error4:
Logger: custom_components.bluetti_bt.bluetti_bt_lib.bluetooth.device_reader
Quelle: custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py:140
Integration: Bluetti BT (Dokumentation, Probleme)
Erstmals aufgetreten: 00:56:41 (1 Vorkommnisse)
Zuletzt protokolliert: 00:56:41
Polling timed out. Trying again later
```

**Comment by TobiGitHubi** [comment]
Sorry, wrong Bluetti integration...
