### ISSUE TITLE
[Bug]: Integration broken for EP600 with current Firmware (IOT v9043,12) 

### ISSUE THREAD

**Issue by carstenschroeder** [Patrick762/hassio-bluetti-bt#51]
### What happened?

The integration does not load. The device name is not EP600... anymore but PBOX... instead.

### Version

0.0.11

### What device are you seeing the problem on?

EP600

### What bluetooth connection are you using?

ESPHome bluetooth proxy

### Have you changed the integration settings?

false

### Relevant log output

```shell
Error setting up entry PBOX22460... for bluetti_bt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/__init__.py", line 55, in async_setup_entry
    coordinator = PollingCoordinator(hass, address, device_name, polling_interval, persistent_conn, polling_timeout, max_retries)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 153, in __init__
    bluetti_device = build_device(address, device_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bluetti_mqtt/bluetooth/__init__.py", line 28, in build_device
    if match[1] == 'AC200M':
       ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Patrick762** [comment]
You can try beta Version 0.0.15 or 0.0.16. This includes a temporary fix for this

**Comment by Patrick762** [comment]
New release 0.0.17 is now available with auto-detection instead of the dropdown

**Comment by carstenschroeder** [comment]
Works great thanks!
