### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mambovipi** [Patrick762/hassio-bluetti-bt#82]
### What happened?

hi Patrick, just tried to connect my new EP600. Doesn't work :( No Entities. 
After the last firmware update the device appears as PBOX... instead of EP600... ,  I noticed.
 Some general changes there?

### Version

0.0.17

### What device are you seeing the problem on?

EP900

### What bluetooth connection are you using?

USB dongle

### Have you changed the integration settings?

false

### Integration settings (if you changed them)

```text
EP 600
BT RasPi4
```

### Relevant log output

```shell
2024-03-29 15:56:14.933 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry PBOX2246000632802 for bluetti_bt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/__init__.py", line 55, in async_setup_entry
    coordinator = PollingCoordinator(hass, address, device_name, polling_interval, persistent_conn, polling_timeout, max_retries)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bluetti_bt/coordinator.py", line 153, in __init__
    bluetti_device = build_device(address, device_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bluetti_mqtt/bluetooth/__init__.py", line 28, in build_device
    if match[1] == 'AC200M':
       ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Patrick762** [comment]
You could test the latest beta version on HACS. There's a fix for the PBOX update

**Comment by mambovipi** [comment]
Thx Patrick. Works like a charm! No issues yet :)
